title: StravaAPILibary Documentation
description: Comprehensive .NET library for Strava API integration
baseurl: "/StravaAPILibary"
url: "https://your-username.github.io"

# Jekyll Configuration
markdown: kramdown
highlighter: rouge
permalink: pretty

# Collections
collections:
  api:
    output: true
    permalink: /api/:path/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Custom CSS - Dark Theme
custom_css:
  - /assets/css/theme.css
  - /assets/css/dark-theme.css
  - /assets/css/syntax.css

# Navigation
nav:
  - title: Home
    url: /
  - title: Getting Started
    url: /articles/getting-started/
  - title: Authentication
    url: /articles/authentication/
  - title: Examples
    url: /articles/examples/
  - title: API Reference
    url: /api/

# Social links
social:
  github: your-username/StravaAPILibary
  twitter: your-twitter-handle

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/ 